compile1:
    gcc Q1_part1.c && ./a.out
# 	Compile your code for first part here

run1: compile1
# 	 Execute part 1 here

compile2:
    gcc Q1_part2.c -lpthread && ./a.out
# 	Compile your code for second part here

run2: compile2
#	Execute part 2 here

