compile1:
# 	Compile your code for first part here
    gcc Q1_part1.c && ./a.out

run1: compile1
# 	 Execute part 1 here

compile2:
# 	Compile your code for second part here
    gcc -lpthread Q1_part2.c && ./a.out

run2: compile2
#	Execute part 2 here

